### ISSUE TITLE
svg fill

### ISSUE THREAD

**Issue by leolo69** [thednp/kute.js#10]
Hello again,
just a quick question. can i use kute to animate the polygon fill of a svg? i didn't find it in your documentation. so maybe you have an idea. :-)

thanks again
alex

**Comment by thednp** [comment]
This isn't yet supported.

**Comment by leolo69** [comment]
Good to know. Thanks for the quick response.

**Comment by thednp** [comment]
Just a quick update, you now have a SVG plugin, go to the demo site and check it out.
