### ISSUE TITLE
Following your matrix decompose trail

### ISSUE THREAD

**Issue by sebastianwebb** [thednp/kute.js#101]
Hey, 

I've been trawling through various npm packages in the hope of finding a way to decompose a CSS 3d transform matrix back to the transform function values (e.g. rotateX, scaleZ etc), and I keep seeing your posts popping up :)

Did you end up using mat4-decompose or morf.js in the end?

Thanks!
Sebastian

**Comment by thednp** [comment]
None, I rely entirely on `DOMMatrix()` API, for my use case I don't really need it.

**Comment by sebastianwebb** [comment]
OK, thanks for letting me know!
