### ISSUE TITLE
If a tween completes while another is paused, the paused tween is broken.

### ISSUE THREAD

**Issue by b4r3k** [thednp/kute.js#103]
Hi there,

I think I found a bug (or maybe I'm doing it wrong).

As the title explains, trying to resume a paused tween after another tween has completed gives the following error:

> kute.min.js:2 Uncaught TypeError: t[i] is not a function
> &nbsp;&nbsp;&nbsp;&nbsp;at n.update (kute.min.js:2)
> &nbsp;&nbsp;&nbsp;&nbsp;at o (kute.min.js:2)
> &nbsp;&nbsp;&nbsp;&nbsp;at n.resume (kute.min.js:2)
> &nbsp;&nbsp;&nbsp;&nbsp;at HTMLButtonElement.onclick (index.html?key=iFrameKey-b164ae7f-0025-187e-7d36-a6b7a65dc4cc:33)

Is it normal and is there a way to prevent it?

I've created a codepen to easily test it:
https://codepen.io/b4r3k/pen/wvGMQBZ

**Comment by thednp** [comment]
Hi there.

I suspect this must be related to the new queue functionality for the execution context. I can't think of a way around this, but I will provide a fix and let you know.

**Comment by thednp** [comment]
[Try this](https://codepen.io/thednp/pen/rNexEvw) and lemme know.

**Comment by b4r3k** [comment]
It works like a charm, thanks :)

**Comment by thednp** [comment]
Will be published asap then, cheers.
