### ISSUE TITLE
Shapes that are not topologically circles are handled poorly

### ISSUE THREAD

**Issue by KingSupernova31** [thednp/kute.js#106]
Here is a ring being morphed into an identical ring. The animation should be do nothing visually, but instead it flashes completely black. If you change the morphIndex property, you seem to get different but equally poor animations.

https://codepen.io/KingSupernova/pen/wvoawqB

**Comment by thednp** [comment]
You are 2-3 years behind. Perhaps check the demo and the updated npm/cdn and git?

**Comment by KingSupernova31** [comment]
Whoops, thanks. That doesn't solve the issue though. I updated the codepen with the most recent Kute version, the problem is still occurring.

**Comment by thednp** [comment]
You have two components for SVG Morph, only one is available on CDN, but sources are all available on CDN and npm

* [SVG Morph](https://thednp.github.io/kute.js/svgMorph.html) (our default component)
* [SVG Cubic Morph](https://thednp.github.io/kute.js/svgCubicMorph.html) (the other younger component)

Also you have the [SVGPathCommander](https://github.com/thednp/svg-path-commander) you can play to adjust your shapes.

Now, you need to check some stuff, morphIndex is no longer needed, I linked you the components above so you should have a look, see what's what. Read.

**Comment by KingSupernova31** [comment]
> You have two components for SVG Morph, only one is available on CDN, but sources are all available on CDN and npm
I'm not sure what you mean. You're saying I'm missing something?

> Now, you need to check some stuff, morphIndex is no longer needed, I linked you the components above so you should have a look, see what's what. Read.
I know that morphIndex is no longer needed, and it's not used in my example code. I was just mentioning that its inclusion changed the behavior in case that helped nail down the issue. There's no need to be condescending.

> (TBH I don't exactly understand what you want to do, morph a shape to itself?)
The code I provided is an **example** of the problem. It's not my actual use-case.

**Comment by thednp** [comment]
It's possible that the default morph component cannot process those paths for some reason I can't figure out, I only suggest to download the code and try the other component, bundled with `kute-extra.js` file, that's a completely different beast, so let me know how that goes.

**Comment by thednp** [comment]
There has been a change to our SVGPathCommander, something related to decimal rounding of path data and ellipse, can you please update a it in your KUTE.js local repo and test your issue? 

That would be great.
Thanks

**Comment by thednp** [comment]
I consider this as resolved, especially after ESLint validation was implemented.
