### ISSUE TITLE
SVGTransform doens't working on v2.1.2

### ISSUE THREAD

**Issue by joaoggnogueira** [thednp/kute.js#107]
I'm using this import statement 

`import KUTE from "kute.js"`

when I run this code

```
KUTE.allTo(
      "rect, circle",
      { svgTransform: { rotate: 360 } },
      { repeat: 1, yoyo: true }
    ).start();
```

over this SVG

```
<svg id="morph-example" xmlns="http://www.w3.org/2000/svg">
    <rect x="100" y="100" width="100" height="100" fill="blue" />
    <circle r="50" cx="400" cy="150" fill="red" />
  </svg>

```

Literally, nothing is happening, whats happening?

`"kute.js": "^2.1.2",`

Codepen

https://codepen.io/joao_nogueira/pen/BaRxqjN

**Comment by joaoggnogueira** [comment]
The KUTE.js works fine on version 2.0.2, but 2.1.2 dont

**Comment by thednp** [comment]
**SVGTransform** is not included in the default distribution file anymore. You can use the `kute-extra.js` file for that.

**Comment by joaoggnogueira** [comment]
@thednp Thanks for reply
