### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by itpropro** [thednp/kute.js#108]
Hey,
Thanks for your hard work on this great animation library!
I wondered if there are any plans to make type definitions available in order to use it properly in TypeScript based projects?

**Comment by thednp** [comment]
@itpropro I've made a `tsconfig.json` which generates a `typescript/index.d.ts` file, please test latest master and provide feedback.

Thanks

**Comment by thednp** [comment]
2.1.3 now has Typescript TYPES.

**Comment by j-vallet-onesys** [comment]
Hi, thanks for the hard work on this awesome library.

However, I have some problems for compiling it on an Angular project.

It could not resolve de dependencies from svg-path-commander :
![image](https://user-images.githubusercontent.com/60925708/144650791-00fcc84a-e5b6-4da7-95a1-af5fd3bdc255.png)

If I replace the full js path by `svg-path-commander` it's working

There is another error on the Version.d.ts :
![image](https://user-images.githubusercontent.com/60925708/144651325-41a9b455-8b72-4ea0-9540-701bd246cf63.png)
![image](https://user-images.githubusercontent.com/60925708/144651378-594f0c77-43fa-4bb3-bd03-514eedcc2cff.png)

For reproducing I have just made a `ng new test-kutejs`, installed kute.js package and imported it in the app.component.ts like this :
`import KUTE from 'kute.js';`

**Comment by thednp** [comment]
I'm currently working on SVGPathCommander and KUTE.js, so feel free to provide any suggestion in regards to TypeScript, I'm still new to this.

**Comment by thednp** [comment]
> If I replace the full js path by svg-path-commander it's working

@j-vallet-onesys can you please explain what do you mean?

**Comment by j-vallet-onesys** [comment]
I have replaced this import statements like this in svgMorph.d.ts in the node_module directory of my app and there is no more errors :
![image](https://user-images.githubusercontent.com/60925708/144813272-a58c8361-97af-495d-858b-dc5ce79fe86b.png)

I'm not really used to compile javascript application descriptions for typescript too, but I will make some tests on my side too.

**Comment by thednp** [comment]
@j-vallet-onesys 
Please update to the latest and report any issue.

**Comment by JoshuaAlzate** [comment]
I attempted to add the library to my Angular project, but the problem above persisted.

**Comment by thednp** [comment]
KUTE.js codebase need to be reworked with Typescript. I'm planning a major rework and major version release in the next couple of weeks, I already have SVGPathCommander done.
