### ISSUE TITLE
SVGMorph problems

### ISSUE THREAD

**Issue by Xyndra** [thednp/kute.js#111]
I am having real troubles with tthe morphing, here is a link: https://codepen.io/xyndra/pen/LYeWOvN

**Comment by thednp** [comment]
Reading and understanding [the demo/docs](https://thednp.github.io/kute.js/svgMorph.html) is key, I suggest not skipping it next time.

**Comment by Xyndra** [comment]
I have now edited the code pen and removed the sub-shapes from the sun(all in all making it two single shapes), and it still doesn't work(I am sorry if I overlooked a step, I am a bit to stupid for the docs)

**Comment by thednp** [comment]
```js
import KUTE from "https://cdn.jsdelivr.net/npm/kute.js@2.2.2/dist/kute.esm.js";

const sunToMoon = KUTE.fromTo(
      "#sun",
      { path: "#sun" },
      { path: "#moon" },
      { duration: 1000 });
const moonToSun = KUTE.fromTo(
      "#sun",
      { path: "#moon" },
      { path: "#sun" },
      { duration: 1000 });
sunToMoon.chain(moonToSun);
moonToSun.chain(sunToMoon);

async function test() {
  sunToMoon.start()
}


test();
```

This works for me, but you need to fix your paths, something is wrong.

**Comment by Xyndra** [comment]
ok, thanks a lot

**Comment by Xyndra** [comment]
I found the problem! The morph precision was much to low
