### ISSUE TITLE
prebake animations/tweens for svg morphs

### ISSUE THREAD

**Issue by HannesGitH** [thednp/kute.js#115]
since svg morphs are quite computationally expensive it would be nice to be able to calculate the morphs and export them (e.g. to .json) similar to Lottie Files, so we could directly load and run the prebaked morphs without needing to recalculate them on every client

**Comment by thednp** [comment]
You can already and easily export them. just do 
```
const tween= KUTE.fromTo(...args)

const from = JSON.stringify(tween.startValues.path);
const to = JSON.stringify(tween.endValues.path)
`

Reuse them in your future tweens ;)

**Comment by HannesGitH** [comment]
so i would call them something like 
```js
const parsedTween = KUTE.fromTo('#elem', 
    JSON.parse(from),
    JSON.parse(to)
)
```

and the calculation would be much faster?
(currently its unfeasable for me to use this package since everytime i refresh the page it blocks to page load for like 1sek per svg morph (and i have a couple))

**Comment by thednp** [comment]
It only takes a few milliseconds to parse, the data is already there.

**Comment by HannesGitH** [comment]
> It only takes a few milliseconds to parse, the data resulted from CPU gymnastics is already there.

thats what i wanted to hear :) nice!
