### ISSUE TITLE
how can i use onComplete on this code

### ISSUE THREAD

**Issue by GeMarVi** [thednp/kute.js#120]
I need something to happen at the end of the first transform but I can't find the correct syntax
Could you help me to write the way to use onComplete?

import KUTE from "kute.js"

const target = document.querySelector("#desktop")
const targetTwo = document.querySelector("#phone")

const animation = KUTE.fromTo(target, 
  { path:  target }, 
  { path: "M0,349.14H477.35v11.44c0,8.34-6.48,15.11-14.45,15.11H14.45c-8,0-14.45-6.77-14.45-15.11Z" }, 
  { duration: 3000 },
)

const animationTwo = KUTE.fromTo(target, 
  { path:  target }, 
  { path: "M0 349.14 L42.51 321.25 L438.04 321.25 L477.35 349.14 L0 349.14 Z" }, 
  { duration: 3000 },
)
animation.chain(animationTwo).start();

**Comment by thednp** [comment]
It's not that far into the [wiki](https://github.com/thednp/kute.js/wiki/Tween)

**Comment by GeMarVi** [comment]
I have tried in many ways to write the onComplete function but it does not work, the documentation does not clarify how to use it, it gives me errors that onComplete is not a function, so I ask you for a simple example of how to use it

**Comment by thednp** [comment]
```js
const animation = KUTE.fromTo(target,
{ path: target },
{ path: "M0,349.14H477.35v11.44c0,8.34-6.48,15.11-14.45,15.11H14.45c-8,0-14.45-6.77-14.45-15.11Z" },
{ duration: 3000, onComplete: () => console.log('here it is') }, // <===
)
```

**Comment by GeMarVi** [comment]
Oh thank you very much
