### ISSUE TITLE
No more scale-tween after udating to kute.min.js 1.5.0

### ISSUE THREAD

**Issue by leolo69** [thednp/kute.js#22]
Hello,
as i wanted to implement i newer version of your awsome tween-engine i encountered a problem. the scale property does not behave as before. it's not scaling and the positioning animation (translateX as well as translate:[x,y]) is really jerky.

That's my code and i left the minifill.min.js in my html.
 KUTE.fromTo($ameisen,{translate:[20,50],opacity:.6,scale:1.3},{translate:[0,0],opacity:1,scale:1},{duration:3000}).start();
  
Any suggestions?

**Comment by thednp** [comment]
Yes, there is a small fix I applied to fix the scale, and the translate:[x,y] is not working properly with `to()` method only when the current value is something like `translateX` or `translate3d`.

Download the pack and use the UNMINIFIED file for a test.

**Comment by leolo69** [comment]
yes, the unminified version does the trick. so i'll minify it then.
thanks

**Comment by thednp** [comment]
Yes, until all the other potential bugs, we're not rolling a new version yet.

**Comment by leolo69** [comment]
are there any other known bugs i should know of before i use it in client projects?

**Comment by thednp** [comment]
Nothing I am aware of, everything tested and I pointed out MY issue with translate.

**Comment by leolo69** [comment]
super .. then .. i noticed the .to problem a while back and only used fromTo...

thanks

**Comment by thednp** [comment]
Again, do you have a test site or perhaps some fiddle to better describe the translate issue you have encountered? I will probably have to write a debugging documentation chapter about.

**Comment by leolo69** [comment]
http://codepen.io/leolo/pen/PNdrax

her you can see the scale and translate problem with the minified verion

**Comment by leolo69** [comment]
the new minified version works. when i encounter the translate problem i'll let you know.

**Comment by thednp** [comment]
Alright, let's close this down for now.
