### ISSUE TITLE
Support for functionality similar to TimelineMax?

### ISSUE THREAD

**Issue by jackkwong** [thednp/kute.js#25]
thank you for this great library, the demo looks promising and very good alternative to GSAP, wonder what's the recommended way in kute.js to create animation that requires overlapping of tweens 
(eg. from 0s to 5s, change width of object A from 20px to 100px, and from 2s to 4s, change color of Object A from red to blue)

**Comment by thednp** [comment]
It doesn't have a timeline script if that's what you ask for. I think checking all demo and documentation pages will really clear your mind.

**Comment by jackkwong** [comment]
@thednp thank you for the response. Appreciate your moral not to duplicate functionality from other code authors, while animation timeline is a great complexity by itself and seems like a good problem for a animation framework to address to (I'll certainly be happy to see it addressed by KUTE.js).

Thank you for your time, I was wondering why the functionality is not documented since it seems to exist in a merged PR (`https://github.com/thednp/kute.js/pull/19`)

**Comment by thednp** [comment]
@dalisoft committed the timeline script as a starting point for further projects. It works fine for some properties, but for `transform`, so far the current DOM update script is unable to handle independent transforms, which is a unique GSAP Timeline functionality. Again something needs to be done here in a way we don't copy code from GSAP but bring further innovation and / or usability to the table.

By the time I'm writing this, I believe @dalisoft have already coded something to code the above functionality (independent transforms), it's quite the challenge, perhaps he would be willing to contribute with a better timeline in the future.

With KUTE.js as for tween.js, there is a functionality called `.chain()` you can programmatically "link" multiple tweens together without having to calculate an animation delay for each tween, something that would only mimic the functionality of a timeline.

A final note: KUTE.js is designed to provide an animation framework that is efficient, fast and super light, giving you the choice to provide support for legacy browsers, but only if you want to.

**Comment by dalisoft** [comment]
I recommend `.chain()` method, because it works fine. Other way, there will be some timing error. As i contributor of KUTE.js, i can't just steal `TimelineMax` timing hack. Author of this app (KUTE.js) is maked app yourself, included only MIT-Licensed apps as plug-in with credits.
I hope if all browsers when fixes `requestAnimationFrame visiblity change timing error`, we can use my plug-in name called "KUTE Timeline".
I here writed bugs, but nobody worried about it as many developers uses `CSS3 Transition and Animation`

Links: 
* http://stackoverflow.com/questions/36622408/javascript-requestanimationframe-time-jump
* #19 
* http://thednp.github.io/kute.js/

Thanks for using KUTE.js,
with regards,
@dalisoft and specially thanks to
@thednp for amazing KUTE.js

**Comment by jackkwong** [comment]
@thednp @dalisoft: thank you for the good work guys. That's certainly a feat (it even support SVG Morphing)

I've been evaluating multiple animation frameworks for my next project (a single-page application btw), and I have to say KuteJS is one of the best libraries I've seen in the aspect of friendly documentation and well-deigned api, and the work for supporting old browsers is certainly appreciated, I still know some people complaining because something doesn't look good on their IE 9 seriously

+1 for KUTE Timeline

**Comment by thednp** [comment]
@jackkwong as long as you don;t need independent transforms (tweens with different transform props running in paralel for same element), you don't need a timeline script, as @dalisoft also confirms the `.chain()` method is the way to go.

**Comment by groovingtiger** [comment]
Hello @thednp and @dalisoft , I do notice the source looks pretty identical to GSAP. Same methods, properties, etc.. The source of kute.js is little suspect. I notice when GSAP puts something out it shows up on this git. That would be really disappointing to see all the hardwork of GreenSock be used on here. With others like @dalisoft taking credit for someone else's timeline animation platform. That puts me off on using this when the true author of GreenSock is not given any credit for all his great contribution to web animation found mostly in this library. Just my two cents for what its worth, in kindness.

**Comment by thednp** [comment]
@groovingtiger wow that came out of nowhere. You claim is ridiculous, please let me explain why.

FYI: I am against using other people's code as my own, I am an experienced developer that read all about software licensing and copyright. The only one you can blame for such a thing is @dalisoft, he already had some talks with GSAP's devs on such an important matter. So my code is my own, I coded everything on top of tween.js and the open source community.

>I notice when GSAP puts something out it shows up on this git. That would be really disappointing to see all the hardwork of GreenSock be used on here.

So do you have a sample code to showcase such a claim? 

>That puts me off on using this when the true author of GreenSock is not given any credit for all his great contribution

That isn't 100% GSAP brain the TweenMax, TimelineMax codebase, the true source is [CreateJS](http://www.createjs.com/), you can do a code comparison and you will understand what I mean. Also note that only the synthax seems similar, but again, Velocity uses a similar synthax and many others. 

So again, this code my own and / or of other OPEN SOURCE sources, StackOverflow, and original tween.js source code. Or do you think the tween object initialization is copyrighted by GSAP or something? But I mean what is all this? You fear competition?
