### ISSUE TITLE
Can't use in ES6 - SVG Plugin

### ISSUE THREAD

**Issue by thomasboulongne** [thednp/kute.js#26]
Hi,

I encounter issues in my ES6 project. When I require Kute.js and then the SVG plugin, here what the console outputs (without calling Kute): 
`kute-svg.js:26 - Uncaught TypeError: Cannot read property 'selector' of undefined`
(the plugin does not know Kute).
And when I fix that, this happens: 
`kute.js:37 - Uncaught TypeError: Element not found or incorrect selector: path` 
(still without calling Kute, just requiring it).
Am i missing something?

**Comment by thednp** [comment]
I don't think it's an ES6 standards issue, the UMD have been implemented by a friend of mine @IngwiePhoenix, and he isn't available at the moment to have a look at it, so I'm open to any contribution of any kind for this.

Still, is the `path` an actual selector? The second error triggers when KUTE.js cannot find your element. Perhaps moving your code to your site's `body` would fix this. Please try and let me know.
