### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by selfagency** [thednp/kute.js#27]
Just tried using KUTE for the first time and I get this error on page load. I haven't done anything yet except put script tags linking to the JS in my header.

```
kute.js:26 Uncaught TypeError: Cannot read property 'style' of null
  K.property @ kute.js:26
  (anonymous function) @ kute.js:43
  (anonymous function) @ kute.js:12
  (anonymous function) @ kute.js:14
```

**Comment by thednp** [comment]
Move your JS to the footer. the demo/docs talks about that.
