### ISSUE TITLE
Thinking about a scroll with translation for modern browsers

### ISSUE THREAD

**Issue by thednp** [thednp/kute.js#37]
Modern browsers don't seem to like setting scroll on each and every 16ms, so I am considering featuring a translate transition instead. An example [here](http://codepen.io/ifen/pen/ejcty/).

**Comment by dalisoft** [comment]
:+1: +1

**Comment by dalisoft** [comment]
I am too interesting on it

**Comment by FezVrasta** [comment]
Is this what [skrollr](https://github.com/Prinzhorn/skrollr) does? Maybe you can borrow ideas from it.

**Comment by thednp** [comment]
> Is this what skrollr does? Maybe you can borrow ideas from it.

No, exactly what I mentioned in the first post.

**Comment by dalisoft** [comment]
I think time to make it. As i seen in my app statistic usage starts at IE10 and it supports both 3d transform and transition.

**Comment by thednp** [comment]
It seems our `scroll` property isn't working anymore with more up to date Chrome versions like Canary, so we seem to have to get to it.

**Comment by bresson** [comment]
Unfortunately I can confirm the codepen scroll example fails in Safari:
https://codepen.io/thednp/pen/bVqKmp/

**Comment by thednp** [comment]
I think the next version re-roll might fix that. If Safari is still following the Chromium that is.

**Comment by thednp** [comment]
@bresson I've updated that pen with something new, basically if you can provide a true global scroll target (EG: `HTML/BODY`), it should work perfect.

**Comment by thednp** [comment]
Probably `scroll-behavior: smooth` for now LOL
