### ISSUE TITLE
Anyone interested in an all-in-one bundle?

### ISSUE THREAD

**Issue by thednp** [thednp/kute.js#38]
Main reasons:
- better code organization
- better performance all across the board
- much lighter size

Main downsize: UMD wrappers gonna go.

**Comment by mrksbnch** [comment]
Since all plugins are really small anyway, I think this is a good idea.

**Comment by thednp** [comment]
Thanks for the feedback. I think it's coming with the 1.6 major update.

**Comment by thednp** [comment]
https://thednp.github.io/kute.js
