### ISSUE TITLE
How to set repeat to infinity?

### ISSUE THREAD

**Issue by mvaneijgen** [thednp/kute.js#43]
`repeat: 20 option allows you to run the animation of given tween multiple times. The default value is 0.`

Doesn't talk about it, should I just set it to `999999999999`?

http://thednp.github.io/kute.js/options.html

**Comment by thednp** [comment]
It has to stop [somewhere](https://github.com/thednp/kute.js/blob/master/kute.js#L238) currently set to 9999 max limit. But why `Infinity` really?

**Comment by mvaneijgen** [comment]
I have a wave (as in water) animation on a page which for me doesn't need a limit, but `9999` is fine. Otherwise my bounce rate will be amazing which will probably be not the case.

Thanks for the response.

**Comment by supernova13892** [comment]
I am actually updating my site from GSAP to kute.js and I have a very similar requirement to yours.
Here is my site: [http://theta.crazyripples.com/](http://theta.crazyripples.com/)

Here is what I did to achieve infinity:
```
var tween=KUTE.fromTo(obj,
			{rotate:0},
			{rotate:359},
			{
				duration4200,
				repeat:0,
				complete:function(){
					tween.start();
				}
				
			}
		).start();
```

**Comment by thednp** [comment]
No worry men, I initially set a number like 99999 hoping to solve some recursion, but I found the problem, it was something 1.5 series introduced in the plugins and KUTE.js 1.6 series reintroduces `Infinity` repeat.

**Comment by Skayona** [comment]
For me works next:


`const tween = KUTE.to('#wave-1', {
    path: '#wave-2'
  }, {
     duration: time,
    repeat: 1,
    yoyo: true,
    easing: 'easingCubicOut'
    update: function () {
      if (! tween.options.repeat) {
        tween.options.repeat = 1;
      }
    }
  });

  waves.start();`
