### ISSUE TITLE
API to set defaults?

### ISSUE THREAD

**Issue by t47io** [thednp/kute.js#47]
Something like:
```
KUTE.setGlobalDefault({duration: 1000});
```

would be a great addition, since now I have to manually pass this for every Tween. Thoughts?

**Comment by thednp** [comment]
It's good idea. I will think about it.

**Comment by thednp** [comment]
What about an object in the KUTE main object, something like 
```
KUTE.defaultOptions = {
  delay: 0,
  duration: 700,
  // other options
}
```

**Comment by thednp** [comment]
@t47io I have implemented this feature as I described above, would you be willing to do some tests as soon as I commit?

**Comment by thednp** [comment]
OK, I updated the code, demo, please read http://thednp.github.io/kute.js/options.html to learn how to override options' default values.
