### ISSUE TITLE
FEATURE REQUEST: Adding kute.js to Wikipedia

### ISSUE THREAD

**Issue by dalisoft** [thednp/kute.js#48]
Hi.
As i know VelocityJS have in Wikipedia as animation library..
Would be nice if adding kute.js to Wikipedia.

**Comment by thednp** [comment]
If you refer to github Wiki it can be done relatively fast, but if you refer to actual [wikipedia](https://en.wikipedia.org/wiki/Velocity_(JavaScript_library)) that's something that has to do with wikipedia authors/editors, it is up to them to have it mentioned in their pages.

**Comment by thednp** [comment]
Soon to be written: 

https://en.wikipedia.org/wiki/KUTE.js
