### ISSUE TITLE
Bower/Browserify dependancies with plugins

### ISSUE THREAD

**Issue by danielosborn** [thednp/kute.js#50]
There seems to be a dependency requirement issue In the plugin files in the Bower package.
The KUTE.js/kute-jquery.js file has the correct requirement of the kute.js file. However the other plugins us ` define(['kute.js'], factory);` and `module.exports = factory(require('kute.js'));`
In order for the files to compile correctly with Browserify, I have to change those to reference the kute.js file itself (notice the `./` ): ` define(['./kute.js'], factory);` `module.exports = factory(require('./kute.js'));`

Is that a change that should be made in the plugin files or should I requiring KUTE in a different way?
Here's an example of my js file:
`
require( '../../node_modules/jquery/dist/jquery.js' );
require( '../vendor/KUTE.js/kute.js' );
require( '../vendor/KUTE.js/kute-jquery.js' );
`
Which works file. But when I add:
`require( '../vendor/KUTE.js/kute-css.js' );` (or any of the other plugins files) I get an error: "Cannot find module 'kute.js'"

But when I changed the lines I mentioned above to use the file, they worked and were compiled correctly.

**Comment by thednp** [comment]
You must require exactly as they wrote in the README.md as this

`require( '../vendor/KUTE.js/kute.js' );` doesn't look fine to me.

**Comment by danielosborn** [comment]
I guess the question I was asking is more along the lines of:
When i include the plugins in the same way, only the kute-jquery plugins works. And looking at the top of the files I can see why.

The kute-jquery plugin is looking for the dependency of `'./kute.js'  however the other plugin files are looking for the dependency of `'kute.js'`. 
Here's the top of kute-css.js:
`
(function(root,factory){
  if (typeof define === 'function' && define.amd) {
    define(['kute.js'], factory);
  } else if(typeof module == 'object' && typeof require == 'function') {
    module.exports = factory(require('kute.js'));
  } else if ( typeof root.KUTE !== 'undefined' ) {
    factory(root.KUTE);
  } else {
    throw new Error("CSS Plugin require KUTE.js.")
  }
})(this, function(KUTE){
  'use strict';
`
And here's the top of kute-jquery.js:
`
(function(root,factory){
  // We need to require the root KUTE and jQuery.
  if (typeof define === 'function' && define.amd) {
    define(["./kute.js", "jquery"], function(KUTE, $){
      factory($, KUTE);
      return KUTE;
    });
  } else if(typeof module == "object" && typeof require == "function") {
    // We assume, that require() is sync.
    var KUTE = require("./kute.js");
    var $ = require("jquery");
    
    // Export the modified one. Not really required, but convenient.
    module.exports = factory($, KUTE);
  } else if (typeof root.KUTE !== "undefined" && (typeof root.$ !== 'undefined' || typeof root.jQuery !== 'undefined' ) ) {
    // jQuery always has two ways of existing... Find one, and pass.
    var $ = root.jQuery || root.$, KUTE = root.KUTE;
    factory($, KUTE);
  } else {
    throw new Error("jQuery Plugin for KUTE.js depend on KUTE.js and jQuery");
  }
 })(this, function($, KUTE) {
  'use strict';
`
Obviously different but if you look at line 10 of kute-jquery.js you'll notice that the reference to kute.js is to the file: `./kute.js` and not to just "kute.js".

However the other plugins do not refer to the file, and therefore do not compile correctly. 
Currently (after some more fiddling) I'm requiring the files like so (the only difference is the path to the library is in a separate vendor folder and needs the proper path):
`
var kute = require( '../vendor/kute.js' );
require( '../vendor/kute.js/kute-jquery' );
require( '../vendor/kute.js/kute-css' );
`
And it successfully compiles kute.js and kute-jquery, but errors on kute-css with the error of "Cannot find module 'kute.js'" _because_ it's not using the _file_ reference in `kute-css.js` (per the examples I pasted in above. If I change the two references in that top portion of kute-css.js to `./kute.js` instead of just `kute.js` it compiles perfectly.

**Comment by thednp** [comment]
I am not the one who have done the UMD wrappers, I may have changed them to not work anymore, I really cannot tell.

Can you please fork it, do the changes as you see fit, install from Github and report back?

**Comment by thednp** [comment]
https://github.com/thednp/kute.js/commit/a8ca9a53172a3b225838863aeb910e7aa9b2c422
