### ISSUE TITLE
How to reverse SVG morph?

### ISSUE THREAD

**Issue by supernova13892** [thednp/kute.js#55]
I have a simple SVG with 2 paths.
One is simply hidden(CSS) as required to morph.

I run  `KUTE.to("#path1",{ path: "#path2" }).start();` and now obviously the visibility of the 2 paths has switched.

Now, how do I morph from path2 -> path1 (basically a reverse)?
I tried the obvious:
`KUTE.to("#path2",{ path: "#path1" }).start();` and
`KUTE.to("#path1",{ path: "#path1" }).start();` but they don't seem to work.

Here is a pen of the same: [http://codepen.io/supernova13892/pen/mRjaLL](http://codepen.io/supernova13892/pen/mRjaLL)

**Comment by thednp** [comment]
You can store the value of the `d` attribute of `#path1` before morph, then do a simple

```
KUTE.to('#path1', {path: pathStringFromDAttribute},{}).start();
```
