### ISSUE TITLE
Worker is supported?

### ISSUE THREAD

**Issue by dalisoft** [thednp/kute.js#56]
Hi @thednp.

Working with kute.js is easy and works nice with my vdom-like lib and f7. I building large app and want small size with keeping parallel loading. But i have more than 3k dom nodes, so i want copy properties processing from worker for performance reason. Is this possible?

Below idea,
```javascript
//app.foods.js
import processorList from '../tasks/processedList';
import render from '../rendering/tezRenderer';

const _listOfFoods = [
{ name: 'Pizza', cost: '20USD', deliverTime: 3600, nearestServiceProvider: 'street #n' },
...
//other 3k list
];

const scaleDown (item, i) => {
  return KUTE.to(item, { scale: [1, 1] }, { duration: 2000 }).start();
}

const _processedList = processorList(_listOfFoods).map(render(scaleDown));

export _processedList;


//app.worker.js
const foods = importScripts('app.foods.js');
self.onmessage = function (e) {
const dt = e.data;
foods(dt); // something like this
}

//app.main.js
import _processedList from './app.foods';
import _worker from './app.worker';

_worker.postMessage({...});



```

**Comment by thednp** [comment]
Hey Dav, I don't think this is cross-browser supported, we're gonna dig into that with future versions.

**Comment by dalisoft** [comment]
This is good. About compatibility cares other studio. I should built app in top of technology (never liked, but life forced to learn)
