### ISSUE TITLE
Kute.JS's USP?

### ISSUE THREAD

**Issue by katerlouis** [thednp/kute.js#57]
Kute.JS looks a lot like GSAP on the first 2 looks.
Is there anything unique about kute.js? 

This question is by not meant offensive in any way. I am just curious.

Thanks!

**Comment by thednp** [comment]
GSAP is using sources from TweenJS and some other stuff from [CreateJS](https://github.com/CreateJS/TweenJS) stuff like Timeline, Ticker, event driven rAF, while KUTE.js is a fork of [tween.js](https://github.com/tweenjs/tween.js) with a much more simple architectural prototype and some ideas from D3. Look it up.

**Comment by thednp** [comment]
All clear?
