### ISSUE TITLE
SVG intensive morphing

### ISSUE THREAD

**Issue by stevenspinoza** [thednp/kute.js#58]
Hi, good job with KUTE!
I'm trying to test many SVG libs for remaking my microsite: [stevenspinoza.github.io](url).
I was chaining tweens for emulating the fire animation loop, but I see performance issues.

I have in the chaining,using 6 different svg's:
compliMorph1.chain(compliMorph2);
compliMorph2.chain(compliMorph3);
compliMorph3.chain(compliMorph4);
compliMorph4.chain(compliMorph5);
compliMorph5.chain(compliMorph6);
compliMorph6.chain(compliMorph1).start();

Do you think  I can build this animation using KUTE or do you know other way (Canvas, other libs, etc)

Thanks.

**Comment by thednp** [comment]
```
compliMorph6.chain(compliMorph1).start();
```

should be

```
compliMorph6.chain(compliMorph1);
compliMorph1.start();
```

**Comment by stevenspinoza** [comment]
Hi thednp, thanks for the correction. I tried to optimize the svg's: 50% less points, smaller size and this is an example of each tween:

`var compliMorph1 = KUTE.to(svgPath1, {`
		`path: svgPath2	`	
	`}, {`
		`morphPrecision: 10,`
		`morphIndex: 1000,`
		`duration: 100,`
		`repeat: 0,`
		`yoyo: false,`
		`easing: 'linear'`
	`});`

Even though, I still see that the morphing is lacking performance. I feel it takes ms to process the next shape. Do you have any fire/flames demo or do you recommend to use a canvas approach. I'm seeing the SVG Dom is being changed with KUTE with every tween.

Thanks.

**Comment by thednp** [comment]
The documentation clearly states the `.to()` method to be slower but more practical for simple animations, while for complex and/or chained animations, you need to always use `.fromTo()` to eliminate the lag.

**Comment by stevenspinoza** [comment]
Yes, you are right. I only found that the morphing is not "natural". I tried using the Sinusoidal easings, but still looks 'predictable'.
Originally I use Flash and it took 20 frames. I just exported the 6 keyframes. Do you think if I use the 20 frames, KUTE could handle the performance and would it look more 'natural' to the flames movement?

Thanks.

**Comment by thednp** [comment]
The code is very fast, but depends very much on how you configure your morph.
