### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by Grzegorzsa** [thednp/kute.js#60]
Error when <script src="kute/dist/kute.min.js"></script>is placed in HEAD section of html file. When I place the code before BODY tag everything works fine

**Comment by thednp** [comment]
It should be in the body obviously.

**Comment by Grzegorzsa** [comment]
https://www.w3.org/TR/html4/interact/scripts.html
"The SCRIPT element places a script within a document. This element may appear any number of times in the HEAD or BODY of an HTML document."

Script should handle the situation when it is placed in HEAD section not crash - this is **obviously** a standard.

**Comment by thednp** [comment]
That is obviously jQuery. We don't do that.

**Comment by metaseb** [comment]
> That is obviously jQuery. We don't do that. Why load scripts when you actually need content first? What if some little script crashes and you get no content on the page? So yea, trust me, it's the best in any case.

You answer at this question don't make any sens. 
So, your way is the best way, "Trust me"   ...   No, why?

At least you could describe this behaviour somewhere.
