### ISSUE TITLE
How I can use external svg?

### ISSUE THREAD

**Issue by GuyDiamond** [thednp/kute.js#61]
Hi,
Is it possible to use kute on external svg file in HTML?
When pasting the SVG inline code, it works well, but when I add the object, crashes errors.

Uncaught TypeError: Element not found or incorrect selector: rectangle
    at g (kute.min.js:2)
    at Object.pt [as fromTo] (kute.min.js:2)
    at motion.js:16

**Comment by thednp** [comment]
Maybe if you link the scripts AFTER the SVG Shapes would work?

**Comment by GuyDiamond** [comment]
I'm already linked scripts after objects SVG. Before close tag body. This help me: document.getElementById('sunx').addEventListener('load', function() {
      var sun = this.getSVGDocument();
      var sunRayStart = sun.getElementById('sunRay1');
      var sunRayEnd = sun.getElementById('sunRay2');
      var tween = KUTE.fromTo(sunRayStart ...
