### ISSUE TITLE
complete hook not work =(

### ISSUE THREAD

**Issue by Akiyamka** [thednp/kute.js#62]
To implement a cycled animation a try to use complete hook, but it did not work:
https://jsfiddle.net/akiyamka/m775f3t1/1/

**Comment by thednp** [comment]
`rotateRestart` is not a function.

**Comment by Akiyamka** [comment]
fix https://jsfiddle.net/akiyamka/m775f3t1/2/ ?

**Comment by thednp** [comment]
This should work
https://jsfiddle.net/m775f3t1/3/

**Comment by Akiyamka** [comment]
Thank you very much, this explains why it looked as if the hook did not work
