### ISSUE TITLE
height in % crush width error "Cannot read property 'offsetWidth'"

### ISSUE THREAD

**Issue by Akiyamka** [thednp/kute.js#63]
When i try animate height property of div in %, kute crush width error:
```
Uncaught TypeError: Cannot read property 'offsetWidth' of undefined
    at Object.boxModel (VM917 kute.min.js:2)
    at G (VM917 kute.min.js:2)
    at new ht (VM917 kute.min.js:2)
    at Object.vt [as fromTo] (VM917 kute.min.js:2)
    at VM918 script.js:8
```
Reproduce here: 
https://gist.run/?id=184c8fb470cf21933aba19a54c82d65c

**Comment by thednp** [comment]
What if you would try with the latest version?

**Comment by Akiyamka** [comment]
@thednp In the latest version of the error is gone, it's great! But unfortunately inline the height is still set in pixels instead of %
`height: '100%' ` - > style="height: 44px;" 
I also noticed that height in % calculated from the width
Updated gist:
https://gist.run/?id=184c8fb470cf21933aba19a54c82d65c

**Comment by Akiyamka** [comment]
I think here (:345) should dynamically change offsetWidth or offsetHeight
`return boxValue.u === '%' ? boxValue.v * this[element][offsetWidth] / 100 : boxValue.v;`

**Comment by thednp** [comment]
Nope, the script is intentionally transforming `%` values in pixels to simplify the tween.

**Comment by thednp** [comment]
https://github.com/thednp/kute.js/commit/ba91cd66300142c1da7ed99de9831ea75e27bfa9
