### ISSUE TITLE
How to use morphIndex in examples?

### ISSUE THREAD

**Issue by peterennis** [thednp/kute.js#66]
morphIndex is referred to in the documentation but I do
not see it being used when I search the source.

Could you provide an example?

![capture128](https://user-images.githubusercontent.com/140737/29012959-26449174-7af4-11e7-8a5d-a17dc700f9d4.png)

**Comment by thednp** [comment]
https://codepen.io/thednp/pen/YGayLg

**Comment by thednp** [comment]
@peterennis are we OK now?

**Comment by peterennis** [comment]
Yes, simple multi morph makes it clear.

I did not see it in the default options. Is it missing from the example?

![capture920](https://user-images.githubusercontent.com/140737/29040332-6a6c86e4-7b63-11e7-8770-814872cc1e10.png)

**Comment by thednp** [comment]
The `morphIndex` tween option is optional, but I'm not 100% sure what you need.

**Comment by peterennis** [comment]
I worked through the morph example and liked your optimization code to create "ideal" values.
In the app I just wanted to pass in the best value for the animation.
In your example showed 127, but it was not clear to me where it would be added in code until I
looked at the link examples you sent.

I was asking if it made sense for the Override Ddefault Options' Values to include it e.g.

morphIndex: 127,  //SVG Plugin only - Optional parameter for optimization, Ref: https://codepen.io/thednp/pen/YGayLg

Is there one location with documentation for all of the override options?
Perhaps add a link to there also?

**Comment by thednp** [comment]
With morph SVG there is no reason/argument to override the default `morphIndex` value, or the possibility to override it, as shapes are vastly different in so many ways, we usually do some preparations to normalize them to a point where morph animation is actually "natural" and looks good.

It makes a ton more sense to override the `morphPrecision` option something you can do to balance the quality <-> performance ratio to the best of your need.

I hope that hit the spot.

**Comment by peterennis** [comment]
OK. That makes sense now. So the best process is to find the optimal
morphIndex and then potentially adjust morphPrecision to
suit the device(s).

Thanks!

**Comment by thednp** [comment]
Almost, but `morphPrecision` first, then `morphIndex`.
