### ISSUE TITLE
fromTo with more than two paths?

### ISSUE THREAD

**Issue by patrickbjohnson** [thednp/kute.js#67]
I'm attempting to create an morphing animation stepping through 3 shapes. 

This seems to work fine with two paths but only runs once when 3 paths are provided. Is it possible to animate through three paths with this library using the `fromTo()` method?

Demo: https://codepen.io/pbj/full/qXoPXV/

**Comment by thednp** [comment]
I see `#step-2` is same path with `#step-3`, if I understand your idea correctly, I would do this

```
var tween1 = KUTE.fromTo('#step-1', 
  { path: '#step-1' },
  { path: '#step-2' },
  {
    morphPrecision: 10,
    // morphIndex: 1000,
    duration: 1000,
    // repeat: 100,
    // yoyo: true,
    // easing: 'linear' // the default is already linear
  }
);

var tween2 = KUTE.fromTo('#step-1', 
  { path: '#step-2' },
  { path: '#step-1' },
  {
    morphPrecision: 10,
    morphIndex: 1000,
    duration: 1000,
    // repeat: 100,
    // yoyo: true,
    // easing: 'linear' // the default is already linear
  }
);


tween1.chain(tween2)
tween1.start();
```

Or if you simply want a yoyo morph from `#step-1` to `#step-2`, you can make it even more simple:

```
var tween = KUTE.fromTo('#step-1', 
  { path: '#step-1' },
  { path: '#step-2' },
  {
    morphPrecision: 10,
    // morphIndex: 1000,
    duration: 1000,
    repeat: 1,
    yoyo: true,
    // easing: 'linear' // the default is already linear
  }
);

tween.start();
```

Try these and let me know.

**Comment by thednp** [comment]
@patrickbjohnson are we ok?

**Comment by aaronsmulktis** [comment]
Thanks @thednp, this answer helped a lot!

**Comment by aaronsmulktis** [comment]
Thanks @thednp, your answer (and pkg) was exactly what I was looking for.

@patrickbjohnson I ended up doing this to accomplish what you are asking about:

`var tween1 = KUTE.fromTo(
  "#car1",
  { path: "#car1" }, // from shape
  { path: "#car2" }, // to shape
  {
    // options
    easing: "easingCubicInOut",
    // yoyo: true,
    // repeat: 99,
    // repeatDelay: 1200,
    duration: 800,
    // morphIndex: 85,
    morphPrecision: 10,
    complete: restart()
  }
);

var tween2 = KUTE.fromTo(
  "#car1",
  { path: "#car2" },
  { path: "#car3" },
  {
    easing: "easingCubicInOut",
    // yoyo: true,
    // repeat: 99,
    repeatDelay: 1200,
    duration: 800,
    // morphIndex: 85,
    morphPrecision: 10
  }
);

var tween3 = KUTE.fromTo(
  "#car1",
  { path: "#car3" },
  { path: "#car1" },
  {
    easing: "easingCubicInOut",
    // yoyo: true,
    // repeat: 99,
    repeatDelay: 1200,
    duration: 800,
    // morphIndex: 85,
    morphPrecision: 10
  }
);

tween1.chain(tween2);
// tween1.chain(tween3);
tween1.start();`

(altho at the time of this writing I haven't quite gotten `restart()` to work but I feel I am close
