### ISSUE TITLE
undefined is not an object (evaluating 'r.now') in Safari 9.1.3

### ISSUE THREAD

**Issue by dgcoffman** [thednp/kute.js#71]
After upgrading to React 16, we are seeing a great deal of these errors:

<img width="1060" alt="screen shot 2017-10-18 at 12 54 29 pm" src="https://user-images.githubusercontent.com/1711204/31739684-8e331542-b403-11e7-910b-f8afcce3ef89.png">

Affecting primarily Safari 9.1.3 with `"kute.js": "1.6.5"`

Appears to be throwing on kute.js line 686

``` javascript
this._startTime = t || time.now();
```

because `time` is undefined.

`time` is instantiated from `window.performance` on line 17 with
``` javascript
  // set a custom scope for KUTE.js
  var g = typeof global !== 'undefined' ? global : window, time = g.performance,
```

**Comment by thednp** [comment]
Does it happen with previous versions?

Can you paste the result of `window.performance.now()` from Safari console?

**Comment by thednp** [comment]
I think you need a mock browser.

**Comment by dgcoffman** [comment]
> Does it happen with previous versions?
Yes.

Safari 9.1.3 does define `window.performance`.

<img width="352" alt="screen shot 2017-10-18 at 1 11 49 pm" src="https://user-images.githubusercontent.com/1711204/31740360-f864012c-b405-11e7-99a3-e15f4086093e.png">

**Comment by thednp** [comment]
Must be something with the app you're building. But I do wish to fix this. Is there a way to check time under your environment?

**Comment by dgcoffman** [comment]
> Is there a way to check time under your environment?

What do you mean?

**Comment by thednp** [comment]
`window.performance.now()` returns the exact milisecond it finishes executing

**Comment by dgcoffman** [comment]
Babel transpiles the relevant section of kute.js to

```javascript
!function(n, a) {
            o = [],
            r = a,
            void 0 !== (i = "function" == typeof r ? r.apply(t, o) : r) && (e.exports = i)
        }(0, function() {
            "use strict";
            for (var e, t = void 0 !== n ? n : window, r = t.performance, o = document.body ...
```

**Comment by dgcoffman** [comment]
> window.performance.now() returns the exact milisecond it finishes executing

Yes, the environment is some user's browser.

**Comment by thednp** [comment]
well, replace `n` with `global` for now. but it should work...

**Comment by thednp** [comment]
Please download the demo and do some tests, let me know if you find anything interesting in the console.

**Comment by dgcoffman** [comment]
I'm stumped. ¯\_(ツ)_/¯

**Comment by thednp** [comment]
I think I figured out. Don't do BABEL to KUTE.js, it's ES5 already, so just use as is. A future version will be ES6 so you can do more stuff.
