### ISSUE TITLE
Color morphing not working?

### ISSUE THREAD

**Issue by shenyingzxc** [thednp/kute.js#72]
Hi, thank you for developing such a great plugin!

I'm having some trouble with changing the fill of the path when morphing from one path to another (using the svg plugin). Code I tried seems to match what you have on https://thednp.github.io/kute.js/assets/js/svg.js in terms of using attr: { fill: 'color' }, but the color isn't changing from the initial values used. I wondered if it was because I was using v1.6.2 on CodePen, so I changed it to v1.6.5, but that seemed to break the animation, so I'm now rather stuck. Please help if possible! :D

**Comment by thednp** [comment]
Hi. You need the attr.js plugin to do attributes animation. Check the [docs](http://thednp.github.io/kute.js/attr.html) for more.

**Comment by shenyingzxc** [comment]
Thank you! I understand now and everything works great! :D
