### ISSUE TITLE
import kute-svg empty

### ISSUE THREAD

**Issue by nicoladl** [thednp/kute.js#75]
Hi guys, I'm developing a Vue.JS website and I'm interested to use Kute-svg to morph some svg.
I've installed Kute via npm but when I try to import kute-svg the object is empty.

`import KUTE from 'kute.js`

return the full object

<img width="634" alt="schermata 2018-03-21 alle 13 57 38" src="https://user-images.githubusercontent.com/2022727/37711111-ffbc8cae-2d0f-11e8-9156-e2a549a005c9.png">

`import KUTE from 'kute.js/kute-svg`

return an empty object

<img width="627" alt="schermata 2018-03-21 alle 13 58 26" src="https://user-images.githubusercontent.com/2022727/37711119-0529127a-2d10-11e8-80a2-249de1f778ad.png">

Thank you

**Comment by thednp** [comment]
I don't actually know how to fix this. I will leave this open maybe someone has any idea.

**Comment by laujonat** [comment]
@nicoladl hi, did you ever solve this? I'm running into the same issue with this.

**Comment by thednp** [comment]
@nicoladl I don't actually use this functionality but at least I can say that plugins only fill KUTE main object with additional functionality, If you have a look at the [getting started](http://thednp.github.io/kute.js/start.html) documentation page, I would guess you need to request plugins via `import 'kute.js/kute-svg' from 'kute.js'`, at least according to the contributors from the community who helped me write that part of documentation.
