### ISSUE TITLE
Getting to know kute..

### ISSUE THREAD

**Issue by leolo69** [thednp/kute.js#8]
Hello, 
as promised i took a look at kute.js and i find it very interesting indeed.
i'm trying to use kute.js but already run into some problems, which are certainly user related errors. :-)

1.) anonymous function calls
i tried something like complete:function(){..do something ..} ... but apparently you have to call a specific function by name .. am i right?

2.) complete event fires before real ending

i have the following tween and a function which should be called by completion. but the showText()-function ist called immediately.

	var tweenSlide0 = KUTE.fromTo(
		$target,
		{left:0},
		{left:-300},
		{delay:3000},
		{easing: 'easingCubicOut'},
		{duration:10000},
		{start:hideText(1)},
		{complete:showText(1)}
		)
		.start();

	function showText(num){

		console.log("showText");
		var tweenFadeIn2 = KUTE.fromTo($s_texte[num],{opacity:0}, {opacity:1},{duration:100}).start();
	}

3.) specific order
sometimes duration is accepted as argument, sometimes not. it depends on the positioning inside the tweencall. in my second problem description you see a duration of 10000 (i wanted to see an effect) but no change in the tween duration happens. strange.

as mentioned above... the tweening engine seems pretty neat and as for the kb size very "sexy". i have to figure out only the best handling.

thanks
alex

**Comment by thednp** [comment]
1. try something like `complete: functionName` and define the function
elsewhere
2. when you define callbacks as options, you cannot specify arguments,
specify arguments in the function definition
3. check the documentation, some methods from tween.js have been dropped to
simplify the code.

Thanks for the heads up and let me know how it goes :)

**Comment by thednp** [comment]
Question: do you think we should manage callbacks via methods? like tweenjs does?

**Comment by leolo69** [comment]
Thanks for the quick response.

Callbacks via methods could be nice.Also the possibility to pass arguments would be a good thing.

is there a specific order and amount of parameters for the kute tween?

when i do 
KUTE.fromTo($target,{left:0},{left:-300},{delay:3000},{complete:showText}).start(); 

it delays 3 seconds but does not call the function.

but by deleting the delay part the complete-function is called.

**Comment by thednp** [comment]
Not possible, see a working example here.
http://codepen.io/thednp/pen/xwqYbX/

**Comment by leolo69** [comment]
sorry .. you're right ... delay and callback should be inside the same brakets ... thanks a lot!

**Comment by thednp** [comment]
Yea, you found it! So yes, the synthax is a bit different than what you used to, maybe GSAP?

**Comment by leolo69** [comment]
Yes, GSAP, but as some ad publisher still are way to "allergic" to kilobytes i try everything to reduce filesize .. thank you again.

**Comment by thednp** [comment]
You're welcome, and anytime you need help.

**Comment by leolo69** [comment]
yeah did it ... the banner is running ... nearly ... i'm again fighting my best buddy ie9
i'm using only movement "left" and opacity. is there a reason why it doesn't work in ie 9?
i read, that kute.js has to know the actual browser. i thought this was only necessary when using 3d transformations/rotations. do i have to use a special ie9-css ?
don't answer me tody .. take your time... have a nice evening ... in germany its nearly 9 pm :-)

**Comment by thednp** [comment]
IE9 doesn't support 3d transformations, only 2d. To target IE9 via JS and without conditional tags in the head, the best would be `var isIE9 = (!window.atob);` but when using a complete polyfill would make IE9 aware of what's `window.atob` and you cannot target the browser properly. An even better, without conditionals could be this http://stackoverflow.com/a/31293352

**Comment by thednp** [comment]
I have a question, do you wrap those ads in iframes by any chance?

**Comment by leolo69** [comment]
yes, i test the ad inside a codepen-iframe. so i have the possibility to do some crossbrowsertesting as i'm working on an apple mac.

**Comment by thednp** [comment]
Well, currently codepen does not allow you to change the class of the `html` tag via conditionals, but you can do the conditionals in the context, then update the html class later, just before invoking KUTE. Let me try to explain:

```
<!--[if IE 8]><div id="my-ads-wrapper" class="ie ie8"><![endif]-->
<!--[if IE 9]><div id="my-ads-wrapper" class="ie ie9"><![endif]-->

<!--[if !IE ]><!--> <div id="my-ads-wrapper" class="modern-browser"> <!--<![endif]-->

<!-- layers go here -->
</div>
```

The next natural phase would be to gather info and cache all the needed environment data, but for now, let's focus on what we have. We have the `<div id="my-ads-wrapper" class="needed-browser-class">`. Now we need to use that in a script linked BEFORE the `<script src="./assets/kute.min.js">`; the script should look like this:

```
<script>
// get the ads wrapper and it's class
var wrapper = document.getElementById('my-ads-wrapper');
var browserClass = wrapper.className;

// if the HTML tag doesn't have the required classes, now it's good time to add the browser class to the HTML tag
if (/ie8/.test(browserClass)){
  document.documentElement.className += 'ie ie8';
} else if (/ie9/.test(browserClass)){
  document.documentElement.className += 'ie ie9';
}
</script>
```
Remember, the above script goes in the `</body>` just before linking KUTE.js script, so that KUTE registers internally a legacy browser class.

Now you can go with the usual work, like in my <a href="http://thednp.github.io/kute.js/examples.html#crossbrowser">demo example</a>.

**Comment by thednp** [comment]
I think I have an idea to change KUTE.js internal code so it detects browsers without the HTML class, the http://browserhacks.com site shows an example that's so cool, I think I'm gonna use it.

```
var ieVersion = (function() { if (new RegExp("MSIE ([0-9]{1,}[\.0-9]{0,})").exec(navigator.userAgent) != null) { return parseFloat( RegExp.$1 ); } else { return false; } })();
```

**Comment by leolo69** [comment]
that sounds good ... thank you very much for your support. later i will try your first solution. as i'm coming from the webdesign side programming is not really my biggest skill. ;-)

**Comment by thednp** [comment]
Let's close this down for now :)

**Comment by thednp** [comment]
FYI: I am updated the way KUTE.js detects the browser, you can re-download and check again. Now your code should be more simple:

In your code, instead of checking for `className`
```
var isIE = /ie/.test(document.documentElement.className),
      isIE8 = /ie8/.test(document.documentElement.className);
```

Now you should do this:

```
var isIE = (new RegExp("MSIE ([0-9]{1,}[\.0-9]{0,})").exec(navigator.userAgent) != null) ? parseFloat( RegExp.$1 ) : false,
      isIE8 = isIE === 8,
      isIE9 = isIE === 9;
```

Then target the browsers with properties they support. I am now updating documentation.

**Comment by leolo69** [comment]
nice!

**Comment by leolo69** [comment]
hi there, just one additional questions ... as publishers often forbid external references i wonder if there's a way to avoid "https://cdn.polyfill.io/v2/polyfill.js?features=default,getComputedStyle|gated" or to load it locally? by reading the polyfill documentation i doubt it but maybe who knows ;-)

**Comment by thednp** [comment]
Yes, use this https://github.com/thednp/minifill it's all the polyfill KUTE.js needs to work on legacy browsers.

**Comment by leolo69** [comment]
great! your'e my hero. the minified minifill version doesn't seem to work with ie9 but the big one does. what a relief. keep the good work and very kind assistance!

**Comment by thednp** [comment]
Let me try to minify that flle again. Could be a problem with the minify script,

**Comment by leolo69** [comment]
just did it with an online compressor .. now it works .. thank you very much!!!!

**Comment by thednp** [comment]
What was the error and your compressor of choice please?

**Comment by leolo69** [comment]
frist i took out all the comments manually, because sometimes compressors mess with tat. than i added your license line. you can find the compressor on http://refresh-sf.com/

**Comment by thednp** [comment]
Something is wrong and I cannot figure it out.  

Linking this works
```html
<script src="https://cdn.jsdelivr.net/minifill/0.0.2/minifill.min.js"> </script>
```
but this doesn't

```html
<script src="./assets/js/minifill.min.js"> </script>
```

With exact same contents.

**Comment by leolo69** [comment]
strange ... you don't image how often i wish i had become a pizza maker due to my italian roots rather than loosing sleep over bytes and endless browserbugs ;-)

**Comment by thednp** [comment]
Should work for you as well, maybe you had a typo somewhere.

**Comment by leolo69** [comment]
Thanks again

**Comment by thednp** [comment]
Well then, how did it go?

**Comment by leolo69** [comment]
Hi, here's a link. as i'm using codepen only for crossbrowsertesting purpose i put my banner into an iframe construction (publisher alike). the ad is still "work in progress" and no big deal. only an html5 adaption of a flash ad a befriended flash designer did a year ago.

**Comment by leolo69** [comment]
24kb of filesize kut.min.js+minifill.min.js ... great job...!

**Comment by leolo69** [comment]
by leaving "// KUTE.js | dnp_theme | MIT-License" in the javascript file your license agreement should be respected.. am i right?

**Comment by thednp** [comment]
Yes, that is fine, but you didn't share a link to your pen, you made me curious :)
