### ISSUE TITLE
Conflict with transform on Firefox

### ISSUE THREAD

**Issue by cgu-pix** [thednp/kute.js#80]
Hi,

I use SVG plugin. When morphing is running, the css transform property on an another element (to do a flip card) doesn't work. There is like a glitch. It seems there is a conflict. 
If I disable KUTE.js or as soon as morphing is complete, everything works fine, the flip doesn't glitch anymore.
And this problem is only on Firefox. With Chrome, everything looks good, both svg morphing and css transform property at the same time.

Have you ever encountered this problem? Is there a workaround for this ?

Thanks

**Comment by thednp** [comment]
I don't know, do you have a demo with the issue?

**Comment by cgu-pix** [comment]
Yes, but could you give me an email that I can use to send you a private access ?

**Comment by thednp** [comment]
Just make a new pen with the issue, it will take a few minutes to setup.

**Comment by cgu-pix** [comment]
Here the pen : https://codepen.io/anon/pen/qyBpBz
With Firefox, the grey flip card don't work

**Comment by thednp** [comment]
That isn't JavaScript animation powered by KUTE.js, it's just some CSS3. You need to do some Google.

**Comment by cgu-pix** [comment]
Yes, I know that.
The problem is when I enable KUTE.js, the transform doesn't work anymore. If I disable it, everything works fine. The transform of the flip card is ok. So I think there is a conflict with KUTE.js, but I didn't find why...
