### ISSUE TITLE
How to stop ticker()?

### ISSUE THREAD

**Issue by diafygi** [thednp/kute.js#81]
Does anyone know how to stop the `ticker()` when all your animations have stopped?

Example:
```
<html>
  <body>
    <div id="myDiv"></div>
    <script src="kute.js"></script>
    <script>
      var tween = KUTE.fromTo("#myDiv", {left: 0}, {left: 100}, {duration: 100});
      tween.start();
      window.setTimeout(function(){ tween.stop(); }, 200);
    </script>
  </body>
</html>
```

If you run a performance monitor in your browser debugger, you can see `requestAnimationFrame` still being called even after the animation is done and and `tween.stop()` has no effect (which I guess makes sense because the tween is already done by the time `tween.stop()` is called).

![screenshot_2018-07-16_01-51-35](https://user-images.githubusercontent.com/643187/42750187-308cdcf8-889b-11e8-9370-3201f7472458.png)

How can I stop the ticker after an animation is done?

**Comment by thednp** [comment]
The `ticker` is set to stop automatically after all tweens are finished, perhaps you have something still running outside the viewport?

**Comment by diafygi** [comment]
Hmmm, then why am I seeing the call to `requestAnimationFrame` in the debugger in the above example even after the tween is finished?

(the full example html is in the initial bug post, it's super short)

**Comment by thednp** [comment]
It seems that Google Chrome doesn't have this issue, just Firefox and MS Edge continue to use `ticker` after animation is finished. At this point I think these browsers don't use the `cancelAnimationFrame` properly.

**Comment by diafygi** [comment]
Hmmm, in Chromium on Linux, I'm still seeing the same behavior as Firefox (see screenshot below).

From digging into the code, it looks like `!tweens[length] && stop();` is where the issue is[1]. When I debug this line in the initial example, `tweens[length]` is `1`, so `stop()` never fires.

[1] - https://github.com/thednp/kute.js/blob/master/kute.js#L483

![screenshot_2018-07-17_09-59-18](https://user-images.githubusercontent.com/643187/42833550-38532afa-89a9-11e8-897a-6619549b55bd.png)

**Comment by thednp** [comment]
Can you try to add stop after a 30-60 miliseconds timeout?

**Comment by diafygi** [comment]
Ok, so I think I know what's going on:

* In `close()`, it checks to see if there's any tweens left and stops if there's none (`!tweens[length] && stop();`)[1].
* However, `tweens` gets emptied in `ticker()`[2], so a race condition happens where `close()` runs before `ticker()` can remove the complete tween.

Possible solutions:
* In `ticker()`, check to see if tweens is empty before calling `_requestAnimationFrame` again. However, I don't know how this would affect paused/delayed/chained tweens.
* In the public `tween.stop()`[3], add something like `!tweens[length] && stop();` (similar to what's done in `close()`) even if `this` is not playing, so that `tween.stop()` will allow the user to force the ticker to stop if everything is done via the public method `tween.stop()`.

[1] - https://github.com/thednp/kute.js/blob/master/kute.js#L483

[2] - https://github.com/thednp/kute.js/blob/master/kute.js#L265

[3] - https://github.com/thednp/kute.js/blob/master/kute.js#L716

**Comment by thednp** [comment]
OK I put up a small `setTimeout` back in place to make sure we do fire the `stop` callback.

Please do me a favor and test the latest master, let me know how it goes.

**Comment by diafygi** [comment]
@thednp Yep! That works for me.
