### ISSUE TITLE
Is Kute still being actively developed

### ISSUE THREAD

**Issue by Kay2dan** [thednp/kute.js#82]
From the docs, I am really attracted to Kute.js for the new project I am working now. Its mainly between Kute.js or Anime.js.

My two questions are:

1 - Is Kute actively being worked on?

2 - Is it hardware accelerated as the rest of them.

Many thanks for working on this & making such an awesome library!

**Comment by thednp** [comment]
`1 - Is Kute actively being worked on?` YES, it's being improved with every new idea. However we haven't had any new ideas in a long time and not EVERY idea is making it to the development board.

`2 - Is it hardware accelerated as the rest of them.` YES, like anything that uses `requestAnimationFrame`
