### ISSUE TITLE
How can I pause/resume multiple tweens?

### ISSUE THREAD

**Issue by carlotta11** [thednp/kute.js#84]
My tweens are some kind of a storyboard. One after the other are animating different things.
So now I've got 20 different tweens. How is it possible to pause and resume this whole story?
I've tried it with chain like this: 
var tween1.start();
tween1.chain(tween2,tween3,...);

...
tween1.pause();
...

but it pauses only, when tween1 is playing.
Should I pause every tween?
And if so - how do I know where to resume?

**Comment by thednp** [comment]
Make an array with your chained tweens then you can do something like this

```js
myPauseButton.addEventListener('click', function(){
  for (var i=0, l=tweens.length; i<l; i++) {
    if (tweens[i].playing) { tweens[i].pause()  }
  }
}, false)
```

and

```js
myResumeButton.addEventListener('click', function(){
  for (var i=0, l=tweens.length; i<l; i++) {
    if (tweens[i].playing) { tweens[i].play()  }
  }
}, false)
```

Neat?
