### ISSUE TITLE
KUTE.js use without build

### ISSUE THREAD

**Issue by airarm** [thednp/kute.js#87]
I want use KUTE.js without building js 
https://www.screencast.com/t/EUC7wXPpkE4
How I can make it ?

**Comment by thednp** [comment]
**Some suggestions:**

* Use KUTE.js in your site `<body>` (at the end) to get rid of that error, also use all your animation scripting 
* Starting with 1.6.6 we're not actively supporting the jQuery plugin, but it's still available with 1.6.5
