### ISSUE TITLE
Feature Request: Accept plain old Array of Elements for allTo and allFromTo

### ISSUE THREAD

**Issue by mistergibson** [thednp/kute.js#89]
I notice that you only accept a Nodelist for processing multiple element targets. This data type is excruciatingly difficult to work with -- as opposed to the humble Array. I'd really like more flexibility on gathering a list of targets and sending them into a KUTE. I can easily construct an Array of Elements about a dozen ways, which makes the entire thing much more fun.

What would it take to support this additional way of accepting multiple elements?

Thanks

**Comment by thednp** [comment]
Sounds interesting enough for me. It would take some time to queue this up into main focus.

**Comment by thednp** [comment]
@mistergibson 

I'm now working on the next version of KUTE.js, is this OK to you?

```js
function selector(el, multi) {
  try{
    let requestedElem;
    if (multi){
      requestedElem = el instanceof HTMLCollection || el instanceof NodeList || el instanceof Array && el[0] instanceof Element ? el : document.querySelectorAll(el);
    } else {
      requestedElem = el instanceof Element ? el : document.querySelector(el);
    }
    if (requestedElem === null && el !== 'window') throw new TypeError(``);
  } catch(e){
    console.error(`${e}: Element(s) not found or incorrect selector: ${el}`)
  }
  return requestedElem;
}
```

**Comment by thednp** [comment]
https://thednp.github.io/kute.js
