### ISSUE TITLE
Usage with React

### ISSUE THREAD

**Issue by shanekoss** [thednp/kute.js#91]
Having some issues getting this to work with React.  Am I missing something silly?

Recreated this example:

https://codepen.io/thednp/pen/NGpYmM/

here:

https://codepen.io/techsmechs/pen/mYjGEg

but as you can see - no animations occur.  Any ideas?

Thanks!

**Comment by thednp** [comment]
I've added `duration: 15000` to your tween objects and checked the console, the numbers are updating, properly, for some reason your box is either hidden or the background didn't load for some reason.

**Comment by shanekoss** [comment]
Thanks for the speedy reply.

Pilot error - the css plugin needs to be required!

codepen - add:
https://cdnjs.cloudflare.com/ajax/libs/kute.js/1.6.2/kute-css.min.js

in react - add:
require("kute.js/kute-css");

cheers!
