### ISSUE TITLE
Animation on scroll (hide/show button)

### ISSUE THREAD

**Issue by MrGlasspoole** [thednp/kute.js#93]
I'm trying to get rid of jQuery and found this super coll thing called KUTE :-)

I want to hide and show a animated back to top button.
The problem i have is that the animation is running every time i scroll.

If you do this with jQuery it does not happen:
```
if ($scrolling > 150) {
  myElement.fadeIn(3000);
 } else {
  myElement.fadeOut(3000);
}
```
What i have so far:
```
var element = document.getElementById('myElement');

var showBc2Top1 = KUTE.fromTo(element, {opacity:0.01}, {opacity:0.5}, {duration:750});
var showBc2Top2 = KUTE.fromTo(element, {opacity:0.5}, {opacity:0.3}, {duration:750});
var showBc2Top3 = KUTE.fromTo(element, {opacity:0.3}, {opacity:1}, {duration:1500});
var hideBc2Top = KUTE.fromTo(element, {opacity:1}, {opacity:0.01}, {duration:3000, complete: hideCallback});

function hideCallback(){
  element.removeAttribute('style');
}

showBc2Top1.chain(showBc2Top2);
showBc2Top2.chain(showBc2Top3);

window.addEventListener('scroll', function() {
  var scrolling = this.scrollY;
  const stickytop = document.getElementById('header-nav');
  if (scrolling >= 100) {
	stickytop.classList.add('nav-shadow');
  } else {
	stickytop.classList.remove('nav-shadow');
  }
  if (scrolling >= 150) {
	
      if (!showBc2Top1.playing && !showBc2Top2.playing && !showBc2Top3.playing) {
          element.style.display = "inline";
          showBc2Top1.start();
      } // only start the animation if hasn't started yet
  
  } else {

      if (!hideBc2Top.playing) {
          element.style.display = "inline";
          hideBc2Top.start();
      } // only start the animation if hasn't started yet

  }
});
```

So how to do it with KUTE and that there is no interference between show and hide.

**Comment by thednp** [comment]
In this case the `tween.playing` is not enough, I recommend to filter every opacity "state" with a class name check that you insert, for instance `top1animated`, and removed when `hideBc2Top` is complete. Also checking if element is in viewport also helps because you don't want to trigger the entire calculation for the entire page, it's much of a burden for your application.

Hope that helps.

**Comment by MrGlasspoole** [comment]
No doesn't really help because I'm not really good at JS :-(
Took hours to figure out what i have now.
