### ISSUE TITLE
ReactNative 😅

### ISSUE THREAD

**Issue by rborn** [thednp/kute.js#94]
Is it possible to use it with ReactNative ?

**Comment by thednp** [comment]
I don't know, but if your KUTE.js animation code runs after DOM changes, it should be fine.

**Comment by rborn** [comment]
Thnx for the reply - kute depends on DOM, right? if yes it won't work :)

**Comment by thednp** [comment]
Also requires `window` for the `to()` method where `getComputedStyle()` is used.

**Comment by rborn** [comment]
Thanks for explaining 🤗
