### ISSUE TITLE
Is there a kute minified version?

### ISSUE THREAD

**Issue by peterennis** [thednp/kute.js#95]
I am using v1.6.6 and the node_modules does not show any min versions.
Is this correct?
I would like to reduce js loading times.

![Capture683](https://user-images.githubusercontent.com/140737/66153542-94910100-e5d0-11e9-8e4c-7f25ca8dfe54.png)

**Comment by thednp** [comment]
It's not delivered via NPM, you can build your own packages with minify in mind. Future versions will be ES6 modules.
