### ISSUE TITLE
Is there a way to control the time progression of the tween?

### ISSUE THREAD

**Issue by doriantimmermans** [thednp/kute.js#96]
Hi, thank you for this amazing lib !

I was wondering if there is a way to create a slider that would control the progression of the tween animation? Like at one side it's the first .svg, at the other side it's the second .svg, and you can move the slider forward and backward the see the animation progress.

Thank you !!

**Comment by thednp** [comment]
Hello there.

I haven't found this to be important/useful just yet, but it shouldn't be hard to make a slider with values from 0 to 1, stepping 0.001, attach a `change` handler to it and make use of the `KUTE.dom` update functions in the handler. This should only work for `fromTo` tween objects.

**Comment by thednp** [comment]
Update: [check this out](https://codepen.io/thednp/pen/MWWGXVO)
